### ISSUE TITLE
[BUG] Problems with HK TCP Client connection

### ISSUE THREAD

**Issue by soporteHW** [Sinapse-Energia/MIFARE-US#20]
Tested that HK_Set_Config(*) and HK_Connect(*) works fine. 

Wifi gateway was configurated as follow:

![sin titulo](https://user-images.githubusercontent.com/28917446/30172966-7c8f6732-93f6-11e7-9271-1a3747cb95e2.png)

![sin titulo](https://user-images.githubusercontent.com/28917446/30173018-a1af40b4-93f6-11e7-89bf-8b7e80c945c1.png)

WIFI connects with IP: 192.168.1.164 (PC IP address). With Wireshark app capturing paquets,  If we send an HTTP message like this "_MIC_UART_Send_Data(&huart1,(uint8_t*)"GET / HTTP/1.1\r\nHost: 192.168.1.164\r\n\r\n",36,100);_" , the message is sent OK.

![sin titulo](https://user-images.githubusercontent.com/28917446/30173215-3e3c6f6a-93f7-11e7-9649-abfcb7d8e407.png)

I'm trying to simulate am HTTP local server with http://miniweb.sourceforge.net/ in order to validate the TCP connection. It seems works OK, server detects the wifi client connected.
![sin titulo](https://user-images.githubusercontent.com/28917446/30173386-b8aba216-93f7-11e7-833e-647ec4849c92.png)

So, when I send the same HTTP message, it doesn't work.

**Comment by ralcaide** [comment]
The server is running in your local in the port 8000, isn,t? I think your HTTP message should include this port but I'm not sure because is already included in the gateway configuration. Anyway, try it with "GET / HTTP/1.1\r\nHost: 192.168.1.164:8000\r\n\r\n". 
See https://stackoverflow.com/questions/3364144/is-port-number-required-in-http-host-header-parameter

Test also with other HTTP Client trying to perform a request to your server. The google chrome app HTTP Rest Client is very useful to test these kind of things

**Comment by soporteHW** [comment]
Modified the HTTP message format:

 _MIC_UART_Send_Data(&huart1,(uint8_t*)"GET /index.htm HTTP/1.1\r\nHost: 192.168.1.164\r\n\r\n",48,100);_ 

![testinghttpserver](https://user-images.githubusercontent.com/28917446/30203286-ecad59f8-9481-11e7-95b8-2041b786089a.png)

Now, HTTP message are sent OK.

**Comment by soporteHW** [comment]
We receive valid HTTP response with using one example HTTP local server.

As shown in figure, we receive 2383 bytes from HTTP server.

![httpresponse](https://user-images.githubusercontent.com/28917446/30210013-ea48940c-949a-11e7-847a-93384c30d78c.png)
